### ISSUE TITLE
No  hover effect on 'Rules' button and NO padding on 'Tic Tac Toe Game' Card.

### ISSUE THREAD

**Issue by SumitVerma-coder** [malivinayak/Tic-Tac-Toe#11]
There is no hover effect on the Rule button and no padding on 'TIC TAC TOE GAME' Card
![image](https://github.com/malivinayak/Tic-Tac-Toe/assets/112965155/f275e794-5b4f-41b0-94ba-7fcd20393067)
**_PLEASE ASSIGN ME THIS ISSUE UNDER HACTOBERFEST TAG_**

**Comment by malivinayak** [comment]
![image](https://github.com/malivinayak/Tic-Tac-Toe/assets/66154908/85eea73a-2476-4077-bded-44c2a4d0d8f0)

Add padding on both Tic Tac Toe and Result

**Comment by SumitVerma-coder** [comment]
Have made the required changes. Please look into it

**Comment by malivinayak** [comment]
@taylorlottdixon has done UI enhancement with extra feature of showing whose turn currently is
Closing this as a duplicate issue as already #7 PR is merged
