### ISSUE TITLE
Adding Transitions

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/Tic-Tac-Toe#16]
While clicking rules button popup got some transitions ...but clicking ok doesn't have any so i added the same fadeout transition after clicking ok ....check PR

**Comment by ashfaque-mustaque** [comment]
i can make it better by  adding attractive styling ?
can you assign me to make this effective @malivinayak

**Comment by malivinayak** [comment]
@ashfaque-mustaque this issue is find out by @Mouli-3542 and he has already made PR
You can enhance or resolve any other issue
Thank You for your interest
