### ISSUE TITLE
feat: Redesigning the Tic Tac Toe game to give it a refreshing look

### ISSUE THREAD

**Issue by shivam-sharma-03** [malivinayak/Tic-Tac-Toe#18]
As the title suggests, this issue is regarding the styling. So get your CSS skills to work by improving the design of the overall application (or maybe a part of it)

**Comment by shivam-sharma-03** [comment]
A simple yet interesting design using Html CSS
Please assign this issue under Hacktoberfest 2023.
Thank You.

**Comment by malivinayak** [comment]
instead of Redesigning you can work on something which is new or innovative. You can also enhance the current version my adding some unique feature.

**Comment by malivinayak** [comment]
If you have command on markup language you can contribute to https://github.com/malivinayak/Markdown/ Repo
You can make simple contribution too I will accept the PR
