### ISSUE TITLE
feat: Add Sound effect 

### ISSUE THREAD

**Issue by shivam-sharma-03** [malivinayak/Tic-Tac-Toe#19]
As the title suggests, this issue is regarding the adding sound effects to the game when a player wins the game or it is a draw also try to improve the design of the game to give it a refreshing look . So get your Html, CSS and Java Script skills to work by improving the design of the overall application and also adding the sound effect to it.

**Comment by shivam-sharma-03** [comment]
I can add sound effect to the game for both the states(Winning and draw) while give the game  a change in look.
Please assign this issue under Hacktoberfest 2023.
Thank You.

**Comment by shivam-sharma-03** [comment]
hey @malivinayak I have created a PR for this #5 please review it, and attach Hacktoberfest-accepted label to this PR.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by shivam-sharma-03** [comment]
hey @malivinayak I have committed  requested changes again to the PR for this #19 please review it once.

**Comment by malivinayak** [comment]
@Kedarnath-Rothe 

> Please assign this issue to me

This feature is introduced by @shivam-sharma-03 and @shivam-sharma-03 already working on it.
Don't just put same message in every issue. find your own and start working on it if you want.
Thank You.

**Comment by shivam-sharma-03** [comment]
Hey @malivinayak completed the requested tasks, please review and also, please add Hactoberfest-Accepted label to the PR.
