### ISSUE TITLE
feat: Reset button and undo option 

### ISSUE THREAD

**Issue by Avinash-31** [malivinayak/Tic-Tac-Toe#21]
Hey ...
I want to work on this
Can u assign this to me?

**Comment by malivinayak** [comment]
Before start working make sure you have latest code in fork repo.
I am going to merge PR #20 shortly so keep eye and always keep repo updated to avoid unnecessary merge conflicts.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by malivinayak** [comment]
@Kedarnath-Rothe, @Avinash-31 has created this feature idea.
You can also work, I will accept your PR after review and if it is before @Avinash-31 as it is first come first serve.
If you both create PR at same time then i will decide on best feature who have added along with UI enhancement.
Or you can create own issue and start working on it.

**Comment by Avinash-31** [comment]
@malivinayak i have sent the pr..

**Comment by Kedarnath-Rothe** [comment]
Please check my PR

**Comment by malivinayak** [comment]
Completed at #23
