### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by Mouli-3542** [malivinayak/Tic-Tac-Toe#29]
@malivinayak Are u participating in hacksquad ??

**Comment by malivinayak** [comment]
Yes recently joined and created squad
https://www.hacksquad.dev/invite/clnkgxjx4000al708dwha9f7x

**Comment by Mouli-3542** [comment]
Ohh whats the name btw

**Comment by malivinayak** [comment]
> Ohh whats the name btw

200 Success

**Comment by malivinayak** [comment]
@Mouli-3542 you can talk with me {Put message/doubt} at https://github.com/malivinayak/malivinayak/discussions/5
