### ISSUE TITLE
update: update README.md file with latest UI

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Tic-Tac-Toe#4]
currently README.md file contains old UI screenshots. update the [README.md ](https://github.com/malivinayak/Tic-Tac-Toe#readme)File with appropriate details.

**Comment by malivinayak** [comment]
@MustafaKhan026 @ruturaj-gh @tejasviurka @Sankalp20Tiwari

**Comment by SumitMangrati** [comment]
hello i am new to open source contribution and i am willing to learn, could you please assign me this task and guide me through it. I'll be sure to solve this issue

**Comment by SumitMangrati** [comment]
this will be counted as my PR for hacktoberfest 2023 right?

**Comment by malivinayak** [comment]
> this will be counted as my PR for hacktoberfest 2023 right?

Yes
