### ISSUE TITLE
Adding a favicon 

### ISSUE THREAD

**Issue by SumitVerma-coder** [malivinayak/Tic-Tac-Toe#9]
Addition of favicon to website.
![image](https://github.com/malivinayak/Tic-Tac-Toe/assets/112965155/246e4612-559e-4fd2-88c6-bd4fc5822014)
**_PLEASE ASSIGN ME THIS ISSUE UNDER THE HACTOBERFEST TAG._**

**Comment by malivinayak** [comment]
Yes, processed with this.

**Comment by malivinayak** [comment]
Fixed at #10
